import = [
"~/.config/alacritty/catppuccin-frappe.toml",
]

[window]
padding = { x = 15, y = 0 }
dynamic_padding = true
decorations = "buttonless"
startup_mode = "Fullscreen" 

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "Always" }
blink_interval = 500

[mouse]
hide_when_typing = true
