# shellcheck shell=bash
# Hirokiraj 1.0

HIROTHEME_ROSEWATER=#f2d5cf
HIROTHEME_FLAMINGO=#eebebe
HIROTHEME_PINK=#f4b8e4
HIROTHEME_MAUVE=#ca9ee6
HIROTHEME_RED=#e78284
HIROTHEME_MAROON=#ea999c
HIROTHEME_PEACH=#ef9f76
HIROTHEME_YELLOW=#e5c890
HIROTHEME_GREEN=#a6d189
HIROTHEME_TEAL=#81c8be
HIROTHEME_SKY=#99d1db
HIROTHEME_SAPPHIRE=#85c1dc
HIROTHEME_BLUE=#8caaee
HIROTHEME_LAVENDER=#babbf1
HIROTHEME_TEXT=#c6d0f5
HIROTHEME_SUBTEXT1=#b5bfe2
HIROTHEME_SUBTEXT2=#a5adce
HIROTHEME_OVERLAY2=#949cbb
HIROTHEME_OVERLAY1=#838ba7
HIROTHEME_OVERLAY0=#737994
HIROTHEME_SURFACE2=#626880
HIROTHEME_SURFACE1=#51576d
HIROTHEME_SURFACE0=#414559
HIROTHEME_BASE=#303446
HIROTHEME_MANTLE=#292c3c
HIROTHEME_CRUST=#232634

TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="█"
TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="█"
TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=$HIROTHEME_MANTLE
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=$HIROTHEME_TEXT
TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}
# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[fg=$HIROTHEME_BASE bg=$HIROTHEME_PEACH]"
		" #I"
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		"#W "
		"#[$(format regular)]"
	)
fi
# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"$(format regular)"
	)
fi
# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[$(format regular)]"
		" #I"
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		"#W "
	)
fi
# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"hiro_tmux_session_info ${HIROTHEME_GREEN} ${HIROTHEME_BASE} default_separator no_sep_bg_color no_sep_fg_color left_disable"
		#"hostname 33 0 default_separator no_sep_bg_color no_sep_fg_color left_disable"
		"hiro_userhost ${HIROTHEME_MAUVE} ${HIROTHEME_BASE} default_separator no_sep_bg_color no_sep_fg_color left_disable"
	)
fi
