version = 3
auto_upgrade = true
final_space = true

[palette]
  base = '#303446'
  blue = '#8caaee'
  crust = '#232634'
  flamingo = '#eebebe'
  green = '#a6d189'
  lavender = '#babbf1'
  mantle = '#292c3c'
  maroon = '#ea999c'
  mauve = '#ca9ee6'
  overlay0 = '#737994'
  overlay1 = '#838ba7'
  overlay2 = '#949cbb'
  peach = '#ef9f76'
  pink = '#f4b8e4'
  red = '#e78284'
  rosewater = '#f2d5cf'
  sapphire = '#85c1dc'
  sky = '#99d1db'
  subtext0 = '#a5adce'
  subtext1 = '#b5bfe2'
  surface0 = '#414559'
  surface1 = '#51576d'
  surface2 = '#626880'
  teal = '#81c8be'
  text = '#c6d0f5'
  yellow = '#e5c890'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{.Icon}}'
    foreground = 'p:rosewater'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'p:sky'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      home_icon = ''
      max_depth = 3
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:green'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:peach{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:mauve{{ end }}', '{{ if gt .Ahead 0 }}p:yellow{{ end }}', '{{ if gt .Behind 0 }}p:maroon{{ end }}']

    [blocks.segments.properties]
      branch_icon = ''
      branch_max_length = 30
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true
      truncate_symbol = '…'

  [[blocks.segments]]
    template = ''
    foreground = 'p:flamingo'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ if .Error }} {{ .String}}{{ else }}{{ end }} '
    foreground = 'p:green'
    type = 'status'
    style = 'powerline'
    foreground_templates = ['{{ if .Error }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .FormattedMs }} '
    foreground = 'p:green'
    type = 'executiontime'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 50

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'p:teal'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'p:red'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
