"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[palette]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "os"
  style = "powerline"
  foreground = "p:rosewater"
  template = " {{.Icon}}"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  foreground = "p:sky"
    [blocks.segments.properties]
    style = "agnoster_short"
    max_depth = 3
    home_icon = ""
    folder_icon = ""

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  foreground = "p:green"
  foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:peach{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:mauve{{ end }}",
    "{{ if gt .Ahead 0 }}p:yellow{{ end }}",
    "{{ if gt .Behind 0 }}p:maroon{{ end }}"
  ]
  template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    [blocks.segments.properties]
    fetch_status = true
    fetch_upstream_icon = true
    branch_icon = ""
    branch_max_length = 30
    truncate_symbol = "…"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:flamingo"
  template = ""

[[blocks]]
type = "rprompt"
alignment = "right"

  [[blocks.segments]]
  type = "status"
  style = "powerline"
  foreground = "p:green"
  foreground_templates = [ "{{ if .Error }}p:red{{ end }}" ]
  template = " {{ if .Error }} {{ .String}}{{ else }}{{ end }} "
    [blocks.segments.properties]
    always_enabled = true

  [[blocks.segments]]
  type = "executiontime"
  style = "powerline"
  foreground = "p:green"
  template = "  {{ .FormattedMs }} "
    [blocks.segments.properties]
    threshold = 50
    style = "austin"

  [[blocks.segments]]
  type = "node"
  style = "powerline"
  foreground = "p:teal"
  template = "  {{ .Full }} "

  [[blocks.segments]]
  type = "ruby"
  style = "powerline"
  foreground = "p:red"
  template = "  {{ .Full }} "

